namespace Umap.Api.Utilities
{
    public enum Regions
    {
        // CAREER
        // 0 - 99
        CURRENT_SCREEN_INDICATOR = 0,
        TURN_NAME,
        TURNS_LEFT_UNTIL_GOAL,
        GOAL_NAME,
        ENERGY_BAR,
        MOOD_INDICATOR,
        STATS_TABLE,

        REST_BUTTON,
        TRAINING_BUTTON,
        SKILLS_BUTTON,
        INFIRMARY_BUTTON,
        RECREATION_BUTTON,
        RACES_BUTTON,

        // TRAINING
        // 100 - 199
        BACK_BUTTON = 100,

        SPEED_TRAINING_BUTTON_NOT_SELECTED,
        STAMINA_TRAINING_BUTTON_NOT_SELECTED,
        POWER_TRAINING_BUTTON_NOT_SELECTED,
        GUT_TRAINING_BUTTON_NOT_SELECTED,
        WIT_TRAINING_BUTTON_NOT_SELECTED,

        SPEED_TRAINING_BUTTON_IS_SELECTED,
        STAMINA_TRAINING_BUTTON_IS_SELECTED,
        POWER_TRAINING_BUTTON_IS_SELECTED,
        GUT_TRAINING_BUTTON_IS_SELECTED,
        WIT_TRAINING_BUTTON_IS_SELECTED,

        FRIENDSHIP_TRAINING_FIRST,
        FRIENDSHIP_TRAINING_SECOND,
        FRIENDSHIP_TRAINING_THIRD,
        FRIENDSHIP_TRAINING_FORTH,
        FRIENDSHIP_TRAINING_FIFTH,
        FRIENDSHIP_TRAINING_ALL,

        FRIENDSHIP_PARTNER_CARD_IMAGE,
        FRIENDSHIP_PARTNER_CARD_TITLE,
        FRIENDSHIP_PARTNER_CARD_LEVEL,

        TRAINING_POINTS_ADDED_SPEED,
        TRAINING_POINTS_ADDED_STAMINA,
        TRAINING_POINTS_ADDED_POWER,
        TRAINING_POINTS_ADDED_GUT,
        TRAINING_POINTS_ADDED_WIT,
        TRAINING_POINTS_ADDED_SKILLS,

        // EVENT
        // 200 - 299
        EVENT_NAME = 200,
        EVENT_CHOICE_FIRST_OF_TWO,
        EVENT_CHOICE_SECOND_OF_TWO,
        EVENT_CHOICE_FIRST_OF_THREE,
        EVENT_CHOICE_SECOND_OF_THREE,
        EVENT_CHOICE_THIRD_OF_THREE,
        EVENT_CHOICE_FIRST_OF_FOUR,
        EVENT_CHOICE_SECOND_OF_FOUR,
        EVENT_CHOICE_THIRD_OF_FOUR,
        EVENT_CHOICE_FOURTH_OF_FOUR,
        EVENT_CHOICE_FIRST_OF_FIVE,
        EVENT_CHOICE_SECOND_OF_FIVE,
        EVENT_CHOICE_THIRD_OF_FIVE,
        EVENT_CHOICE_FOURTH_OF_FIVE,
        EVENT_CHOICE_FIFTH_OF_FIVE,

        // CAREER_RACE_DAY
        // 300 - 399
        RACE_DAY_RACE_BUTTON = 300,
        RACE_DAY_SKILLS_BUTTON,

        // RACE_LIST
        // 400 - 499
        RACE_LIST_GOAL_NAME = 400,
        RACE_LIST_WEATHER_INFO,
        RACE_LIST_FIRST_RACE,
        RACE_LIST_FIRST_RACE_INFO,
        RACE_LIST_FIRST_RACE_FANS_GAIN,
        RACE_LIST_FIRST_RACE_COMPATEBILITY01,
        RACE_LIST_FIRST_RACE_COMPATEBILITY02,
        RACE_LIST_RACE_BUTTON,
        RACE_LIST_PREDICTIONS_BUTTON,

        RACE_LIST_RACE_DETAILS_RACE_BUTTON,
        RACE_LIST_RACE_DETAILS_CANCEL_BUTTON,
        RACE_LIST_RACE_DETAILS_RACE_INFORMATION,

        // RACE
        // 500 - 599
        RACING_RESULTS_BUTTON = 500,
        RACING_RACE_BUTTON,
        RACING_STATS_PANEL,
        RACING_APTITUDE_PANEL,
        RACING_MOOD_PANEL,
        RACING_STRATEGY_PANEL,

        RACING_FINISH_TAP_TO_SKIP,
        RACING_FINISH_FIRST_NEXT_BUTTON,
        RACING_FINISH_SECOND_NEXT_BUTTON,

        // LEATN
        // 600 - 699


    }
}
